# Étape 1: Image de base Node.js
FROM node:16

# Étape 2: Définir le répertoire de travail
WORKDIR /app

# Étape 3: Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Étape 4: Copier le reste des fichiers de l'application
COPY . .

# Étape 5: Construire l'application
RUN npm run build

# Étape 6: Démarrer le serveur avec node
CMD ["node", "./run-server.mjs"]

# docker build -t nom-de-votre-application .
# docker run -p 3000:3000 nom-de-votre-application
