# Use the official Node.js 16 image as a base
FROM node:18.18.2

# Set the working directory in the Docker image
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install &> build.log

# Copy the rest of your project's files into the Docker image
COPY src ./src
COPY app ./app

# Build your Astro project
RUN npm install -g astro
RUN npm run build

# Expose the port that your app will run on
EXPOSE 8080

# The default command to run when starting the container
CMD ["node", "run-server.mjs"]
